title: Site
tabs:
  #Pages
  articles:
    label: Articles
    icon: dashboard
    columns:
      published:
        width: 2/3
        sections:
          public:
            headline: Articles
            type: pages
            layout: cards
            status: published
            image:
              cover: true
              ratio: 16/9
            templates: article

      articles_drafts:
        width: 1/3
        sections:
          drafts:
            headline: Drafts
            type: pages
            layout: cardlets
            status: draft
            image:
              cover: true
              ratio: 16/9
            templates: article

  #Pages
  others:
    label: Others
    icon: dashboard
    columns:
      other_published:
        width: 2/3
        sections:
          other_published:
            headline: Pages
            type: pages
            layout: cardlets
            status: published
            image:
              cover: true
              ratio: 16/9
            templates:
              - contact
              - about
              - home

      other_drafts:
        width: 1/3
        sections:
          other_drafts:
            headline: Drafts
            type: pages
            layout: cardlets
            status: draft
            image:
              cover: true
              ratio: 16/9
            templates:
              - contact
              - about

  settings:
    label: Configuration
    icon: settings
    columns:
      content:
        type: fields
        width: 2/3
        fields:
          categories:
            label: Categories
            type: tags

          footer:
            label: Footer Pages
            type: pages
          
          pagination:
            label: Pagination number
            type: range
            min: 1
            max: 20
            default: 3

      sidebar:
        sticky: true
        width: 1/3
        sections:
          files:
            type: files
